const enum COLOR_PALETTE {
  SORAME_BLUE = '#2688f0',
  SORAME_BLACK = '#0d0d0d',
  SORAME_WHITE = '#fffffe',
  SORAME_LIGHT_BLUE = '#56a2f3',
  SORAME_DARK_BLUE = '#0f6fd4',
  SORAME_LIGHT_BLACK = '#262626',
  SORAME_GREY = '#F8F8FA',

  SORAME_RED = '#f5222d',
  SORAME_GREEN = '#3CB346',
  SORAME_YELLOW = '#FC8801',

  /** Input */
  SORAME_INPUT_BACKGROUND = '#F4F5F5',
  SORAME_INPUT_PLACEHOLDER_COLOR = '#6E7174',
  SORAME_INPUT_HOVER_BG = '#ECECED',

  /** Header searchTool */
  SORAME_HEADER_SEARCH_BG = '#E5E8EA',
  SORAME_HEADER_SEARCH_BG_HOVER = '#C6CACD',

  /** menu selected */
  SORAME_MENU_SELECTED_BG = '#F0FAFF',
}

export { COLOR_PALETTE };
