export const enum MEASUREMENT {
  // SORAME_INPUT_BORDER_RADIUS_BASE = '32px',
  SORAME_BORDER_RADIUS_BASE = '5px',
  SORAME_HEADER_HEIGHT = '48px',
  SORAME_TRAFFIC_LIGHT_ICO_SIZE = 20,
  SORAME_TREE_CHILD_PADDING = '8px',
  SORAME_CARD_RADIUS = '8px',
  SORAME_MODAL_BORDER_RADIUS = '12px',
}

export const loadingZIndex = 99;
